### ISSUE TITLE
multi tier cache failed 

### ISSUE THREAD

**Issue by chenyou-intel** [pmem/CacheLib#75]
We’ve encountered below error when tried to run multitier_cache example:

<img width="792" alt="1" src="https://user-images.githubusercontent.com/95014274/172106276-83fdcbec-52e2-4477-aae6-1496acdead3d.png">

Code snippet:
<img width="590" alt="2" src="https://user-images.githubusercontent.com/95014274/172106349-8221895e-f56c-4cab-9722-dda5cfcfefd6.png">

**Comment by victoria-mcgrath** [comment]
I am not sure what is the best way to improve this behavior but I’d like to provide you with a quick workaround so that you are not blocked by this issue.

When you configure cache with more than 1 tier, there’s some additional memory reserved for internal needs per each tier. So, in the presence of tiers you can’t allocate a pool whose size is equal to total available size from cache stats. The following formula should work (I tested it for several total sizes and tier numbers) to calculate the max number of bytes available for a single pool:

`size_t maxPoolSize = gCache_->getCacheMemoryStats().cacheSize - ((config.getMemoryTierConfigs().size() - 1) * Slab::kSize);`

The fact that the more tiers you use the less memory you are left with seems to have a more dramatic effect for the caches whose total sizes are relatively small (e.g. 48Mb in your code). But for larger caches (e.g. 1Gb) the decrease in memory available seems negligible. So, if you need a bigger pool, I’d suggest that you also play with the total cache size. 

Please let me know whether you are able to use the provided formula or whether you have any questions. I’ll investigate the issue more and discuss it with the others to make sure that it is fully addressed, if needed, in the meantime.

**Comment by victoria-mcgrath** [comment]
@chenyou-intel The problem was caused by incorrect memory tier sizes that were used to determine per tier pool sizes. I submitted a fix and new regression tests for review (https://github.com/pmem/CacheLib/pull/76). If you want to try the fixed code before the promotion to develop is complete, please use this branch: https://github.com/pmem/CacheLib/tree/issue75.

**Comment by chenyou-intel** [comment]
@victoria-mcgrath Thanks! I'll try this branch
